default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: docs/api
    - id: trailing-whitespace

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.812
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [Deprecated==1.2.11, websocket==0.2.1]

  - repo: local
    hooks:
      # Sort python imports
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system
      # Code formatting
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system
      # Conform all csv files to RFC-4180
      - id: csv
        name: csv
        entry: poetry run clevercsv standardize --in-place
        types: [csv]
        language: system
