name: Hats
author: Oran9eUtan
description: Collectable stylish hats
version: "3.1.0"
output: build
data_pack:
    name: hats_datapack
    load: ["datapack"]
resource_pack:
    name: Hats
    load: ["resourcepack"]
pipeline:
    - beet.contrib.yellow_shulker_box
    - beet.contrib.installation_advancement
    - babelbox.integration.beet
    - mcanitexgen.integration.beet
    - hats.plugins.configuration
    - hats.plugins.hat_loot_tables
    - hats.plugins.item_models
    - hats.plugins.hat_recipes
    - hats.plugins.jinja
    - beet.contrib.render
templates:
  - hats/macros
  - hats/templates
meta:
    namespace: "oran9eutan:hats"
    mcanitexgen:
        load: ["resourcepack/assets/minecraft/textures/**/*.animation.py"]
    babelbox:
        load: ["resourcepack/assets/minecraft/lang"]
        dialect: "excel"
        prefix_identifiers: true
    hats:
        cmd_id: 777
        default_item_head: minecraft:stick
        default_item_inventory: minecraft:leather_helmet
    render:
      data_pack:
        advancements: ["oran9eutan:*"]
        functions: ["oran9eutan:*"]
    installation_advancement:
        author_skull_owner: Oran9eUtan
        icon:
            item: "minecraft:stick"
            nbt: "{CustomModelData: {{ hats.hat.fez.cmd }}}"
