name: Hats
author: Oran9eUtan
description: Collectable stylish hats
version: "2.3.1"
output: build
data_pack:
    name: hats_datapack
    load: ["datapack"]
resource_pack:
    name: Hats
    load: ["resourcepack"]
pipeline:
    - beet.contrib.yellow_shulker_box
    - babelbox.integration.beet
    - mcanitexgen.integration.beet
    - hats.plugins.hat_loot_tables
    - hats.plugins.item_models
    - hats.plugins.datapack_advancement
    - hats.plugins.hat_recipes
    - hats.plugins.jinja
    - beet.contrib.render
templates:
  - hats/macros
meta:
    namespace: "oran9eutan:hats"
    mcanitexgen:
        load: ["resourcepack/assets/minecraft/textures/**/*.animation.py"]
    babelbox:
        load: ["resourcepack/assets/minecraft/lang"]
        dialect: "excel"
        prefix_identifiers: true
    hats:
        cmd_id: 777
    datapack_advancement:
        author_head: "Oran9eUtan"
        icon:
            item: "minecraft:stick"
            nbt: "{CustomModelData: {{ hats.hat.posh_squid.cmd }}}"
    render:
      data_pack:
        advancements: ["oran9eutan:*"]
