github_url = "https://github.com/OrangeUtan/Hats"

[version]
current = "2.3.1"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[file]]
src = "beet-release.json"

[[file]]
src = "datapack/data/oran9eutan/functions/hats/install.mcfunction"
version_template = '{{"major": {major}, "minor": {minor}, "patch": {patch}}}'

[[file]]
src = "datapack/data/oran9eutan/functions/hats/load.mcfunction"
version_template = '{{"major": {major}, "minor": {minor}, "patch": {patch}}}'
