# Configuration for datapack settings
# -----------------------------------
# Used to generate a chat and book menu from which settings can be changed in-game

main: general
scoreboard: hats.cfg
sections:
  general:
    title: "General"
    settings:
      dress_mobs:
        title: Dress mobs
        description: Randomly equip mobs with hats
        type: bool
        default: True
        on_enable: function oran9eutan:hats/loops/dress_mobs
        on_disable: schedule clear oran9eutan:hats/loops/dress_mobs
      pet_conversion:
        title: Pet conversion
        description: Pets can be converted to hats and back
        type: bool
        default: True
        on_enable: function oran9eutan:hats/loops/can_player_convert_pets
        on_disable: schedule clear oran9eutan:hats/loops/can_player_convert_pets
